language: node_js
env:
  global:
  - GH_REF=github.com/globalresiliencepartnership/project-map.git
  - DEPLOY_BRANCH=master
  - secure: "Q+KC0nIni76vTt8UYD6J9evPom5oQwHZlaGM8izDix1NBeiEyLjURTBzesFSe41McDyKPeBPWVPjNVmETJ+pNJ0PFRaFlD91iMT0oFVCC/RYr2rxSIzoASuTff+gGtcp+7oqsnLcVbdMS5j7B9ig/SWanUvhIwFYJJFGmr3aujhjBG91r2Lzi2H0ZsxN4xF744MsRf1RhvuefBNRraSwrfJDopUVSMkhT0NqUW6QGfg8k2h4hgiLHrNzTe7uy2gchrtWvWrkH9UvZ3Lnij4kWO9YoUQKeHUPn4i1exFi4MmPdyfekNnOKTANwv1/GlLmac2PYrvaii1QLmD0edVOqYMjT5n1TCQs5taK7ruvy9WtA/imA6I26jRk7ofyQnai8CxjioW4qGG7PBxux3uRmPG9K6pCV8mgHhKOBMZL639XQz/Y9UIObg4QVVR8yRExUpI7CFUp8HGqyBKZaHMUSuPOwH1xEIRSyVNj3xGEaulmmQi2MwuwWTmDvMXotMBI/+ConRjCRODe5AiCMjBmRKYzsvxAopD6gPicTaHTtMCxhbu2yRa1sisutYHyQOUIYmNHCBjDvynQ1wZALzEEJbgFTocOwgUwkETeVFZMHIdJiAIaS/9hpS+x+NiN5vWOS07O9eleDrqdQqahS6tuvQOHXx2yoR7Lim2kkOQatVA="

cache:
  directories:
    - node_modules
    - source_assets/bower_components
    - bundle/cache

before_install:
- chmod +x ./.build_scripts/deploy.sh
- npm install -g grunt-cli

script:
- grunt prod

after_success:
- ./.build_scripts/deploy.sh